### ISSUE TITLE
Is there a way to upload your own SVG image? 

### ISSUE THREAD

**Issue by sean-mcclure** [jasonwebb/2d-diffusion-limited-aggregation-experiments#2]
I tried placing my own SVG in the folder but it doesn't show the SVG when attempting to grow fractals on text.

**Comment by sean-mcclure** [comment]
I tried placing my own SVG in the folder but it doesn't show the SVG when attempting to grow fractals on text.

**Comment by jasonwebb** [comment]
The SVG parser is extremely finicky and can really only handle very, very simple SVG files. It only handles shapes that are drawn with `<path>` tags, and can't handle grouping. I also found that it will refuse to parse SVG files when some attributes are present on the root node which get added automatically by Inkscape. 

My best advice is to find (and contribute!) a better way of constructing Path objects from SVG input files. You could also try taking a look at the contents [`dla.svg`](https://raw.githubusercontent.com/jasonwebb/2d-diffusion-limited-aggregation-experiments/master/05-svg-input/svg/dla.svg) and modify your file to look as much like it as possible (same attributes, same tag hierarchy, etc).

**Comment by kedionai** [comment]
Makes sense. Thanks for all the info. I’ll have a look and see what I can get working. If I find a general solution I’ll submit a PR to contribute. Cheers.
